 export const GET_MUSIC_START = "GET_MUSIC_START";
 export const GET_MUSIC_SUCCESS = "GET_MUSIC_SUCCESS";
 export const GET_MUSIC_FAIL = "GET_MUSIC_FAIL";

 export const DELETE_MUSIC_START = "DELETE_MUSIC_START";
 export const DELETE_MUSIC_SUCCESS = "DELETE_MUSIC_SUCCESS";
 export const DELETE_MUSIC_FAIL = "DELETE_MUSIC_FAIL";

 export const ADD_MUSIC_START = "ADD_MUSIC_START";
 export const ADD_MUSIC_SUCCESS = "ADD_MUSIC_SUCCESS";
 export const ADD_MUSIC_FAIL = "ADD_MUSIC_FAIL";

 export const EDIT_MUSIC_START = "EDIT_MUSIC_START";
 export const EDIT_MUSIC_SUCCESS = "EDIT_MUSIC_SUCCESS";
 export const EDIT_MUSIC_FAIL = "EDIT_MUSIC_FAIL";